version: '3.8'

services:
  near-contract-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - cargo-cache:/root/.cargo/registry
      - cargo-git-cache:/root/.cargo/git
    working_dir: /workspace
    command: bash
    environment:
      - RUST_LOG=info
    stdin_open: true
    tty: true

volumes:
  cargo-cache:
  cargo-git-cache:
