name: python-lint

on:
  push:
    paths:
      - '**/*.py'
      - '**/pyproject.toml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run linter
        run: |
          # Run Ruff linter
          ruff check --config 0.0.1/pyproject.toml .
          # Run Ruff formatter
          ruff format --config 0.0.1/pyproject.toml . --check
