name: python-lint

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.py'
      - '**/pyproject.toml'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 0.0.1
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run linter
        run: |
          # Run Ruff linter
          ruff check --config pyproject.toml .
          # Run Ruff formatter
          ruff format --config pyproject.toml . --check

      # TODO: Introduce mypy or other static type checker eventually
